// app/layout.tsx

import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import ConditionalSidebarLayout from "@/components/layout/conditional-sidebar-layout"
import Providers from "@/components/providers/session-provider"
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "EnvoyX",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <ConditionalSidebarLayout>{children}</ConditionalSidebarLayout>
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  )
}
